2013/05/24 18:41:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'perdida'' in /Applications/XAMPP/xamppfiles/htdocs/up/framework/db/CDbConnection.php:382
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/up/framework/db/CDbConnection.php(331): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/up/framework/db/CDbConnection.php(309): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/up/framework/base/CModule.php(388): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/up/framework/base/CModule.php(104): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/up/framework/gii/generators/model/ModelCode.php(57): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CFormModel.php(40): ModelCode->init()
#6 /Applications/XAMPP/xamppfiles/htdocs/up/framework/gii/CCodeGenerator.php(154): CFormModel->__construct()
#7 /Applications/XAMPP/xamppfiles/htdocs/up/framework/gii/CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/actions/CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CWebApplication.php(283): CController->run('')
#13 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 /Applications/XAMPP/xamppfiles/htdocs/up/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /Applications/XAMPP/xamppfiles/htdocs/up/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/up/gii/model
HTTP_REFERER=http://127.0.0.1/up/gii
---
2013/05/24 18:53:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "llamadas" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CController.php(271): CController->missingAction('llamadas')
#1 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CWebApplication.php(283): CController->run('llamadas')
#2 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CWebApplication.php(142): CWebApplication->runController('campana/llamada...')
#3 /Applications/XAMPP/xamppfiles/htdocs/up/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/up/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/up/campana/llamadas
---
2013/05/24 18:53:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "llamada" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CController.php(271): CController->missingAction('llamada')
#1 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CWebApplication.php(283): CController->run('llamada')
#2 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CWebApplication.php(142): CWebApplication->runController('campana/llamada')
#3 /Applications/XAMPP/xamppfiles/htdocs/up/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/up/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/up/campana/llamada
---
2013/05/25 17:46:01 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /Applications/XAMPP/xamppfiles/htdocs/up/framework/gii/GiiModule.php:169
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CController.php(264): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CWebApplication.php(283): CController->run('')
#2 /Applications/XAMPP/xamppfiles/htdocs/up/framework/web/CWebApplication.php(142): CWebApplication->runController('gii')
#3 /Applications/XAMPP/xamppfiles/htdocs/up/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/up/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/up/gii
---
